### ISSUE TITLE
Missing a VLAN for storage management

### ISSUE THREAD

**Issue by flozanorht** [openstack-k8s-operators/docs#81]
In https://github.com/openstack-k8s-operators/docs/blob/main/images/network_diagram.jpg there's a "storage mgmt" in the Ceph storage but nothing connects to it. Comparing it with the devpreview2 docs, It seems noth the OSP compute node and something in OCP worker nodes should connect to it as a VLAN.

**Comment by stuggi** [comment]
> In https://github.com/openstack-k8s-operators/docs/blob/main/images/network_diagram.jpg there's a "storage mgmt" in the Ceph storage but nothing connects to it. Comparing it with the devpreview2 docs, It seems noth the OSP compute node and something in OCP worker nodes should connect to it as a VLAN.

this is correct, the storage_mgmt network is not used in ceph use case. you might need it for other storage vendors. we could remove it. this diagram is a generic network diagram which does not specific map to a devpreview release.

**Comment by fultonj** [comment]
> > In https://github.com/openstack-k8s-operators/docs/blob/main/images/network_diagram.jpg there's a "storage mgmt" in the Ceph storage but nothing connects to it. Comparing it with the devpreview2 docs, It seems noth the OSP compute node and something in OCP worker nodes should connect to it as a VLAN.
> 
> this is correct, the storage_mgmt network is not used in ceph use case. 

Technically, the storage_mgmt network is used in the ceph HCI use case by EDPM nodes as described here:

https://github.com/openstack-k8s-operators/docs/blob/main/hci.md#configure-the-networks-of-the-edpm-nodes

In the above scenario, OCP does not have any pods which use the storage_mgmt network though.

> you might need it for other storage vendors. we could remove it. this diagram is a generic network diagram which does not specific map to a devpreview release.

true

**Comment by flozanorht** [comment]
Is the diagram intended to show only the control plane networking requirements? Would'nt it be better to show also data plane networking requirements?

**Comment by fultonj** [comment]
> Is the diagram intended to show only the control plane networking requirements? Would'nt it be better to show also data plane networking requirements?

It does show the data-plane when it says "OSP compute node" on the right. The focus is on control-plane but data-plane is sufficiently covered IMO.

**Comment by flozanorht** [comment]
> It does show the data-plane when it says "OSP compute node" on the right. The focus is on control-plane but data-plane is sufficiently covered IMO.

Then it should have an arrow from compute nodes to storagemgnt on the ceph box, from previous comments here, to be complete and accurate. Or maybe have one "generic" diagram and a second more detailed for the Ceph use case.

**Comment by fultonj** [comment]
> > It does show the data-plane when it says "OSP compute node" on the right. The focus is on control-plane but data-plane is sufficiently covered IMO.
> 
> Then it should have an arrow from compute nodes to storagemgnt on the ceph box, from previous comments here, to be complete and accurate. Or maybe have one "generic" diagram and a second more detailed for the Ceph use case.

No, we've established that the compute node does not talk to the storage mgmt on the ceph box.

**Comment by flozanorht** [comment]
I was reading this comment as confirming there was a need:

> Technically, the storage_mgmt network is used in the ceph HCI use case by EDPM nodes as described here:

But if the diagram is intended to be generic, instead of for hci, then I guess you're right. 

So if there's an external ceph nothing in OpenStack one talks to a ceph storage management network? I would expect something in OpenStack would still create ceph volumes and storage pools, but I'm not a Ceph expert.

**Comment by fultonj** [comment]
> I was reading this comment as confirming there was a need:
> 
> > Technically, the storage_mgmt network is used in the ceph HCI use case by EDPM nodes as described here:
> 
> But if the diagram is intended to be generic, instead of for hci, then I guess you're right.
> 
> So if there's an external ceph nothing in OpenStack one talks to a ceph storage management network? 

Yes.

> I would expect something in OpenStack would still create ceph volumes and storage pools, but I'm not a Ceph expert.

Yes, via the storage network which is in the diagram. I linked the docs which explain.

https://github.com/openstack-k8s-operators/docs/blob/main/hci.md#configure-the-networks-of-the-edpm-nodes
